import type { BinaryNode } from '../WABinary'

export type ConnectionTransportProfile = 'web' | 'native_android'

export type NativeAndroidAppVersion = readonly [number, number, number, number]

/** Immutable Build.* values captured together from one Android installation. */
export type NativeAndroidHardwareProfile = {
	profileId: string
	/** captured = exact Build.* tuple; experimental = catalog tuple pending a real-device capture. */
	quality: 'captured' | 'experimental'
	commercialName: string
	fallback?: boolean
	manufacturer: string
	device: string
	deviceBoard: string
	deviceModelType: string
	osVersion: string
	osBuildNumber: string
	yearClass?: number
	memClass?: number
	oc?: boolean
}

/**
 * Concrete Android identity observed from a real device or controlled emulator.
 * Build.* values come from one verified hardware profile. Per-installation
 * identifiers are generated once with the official UUID encoding and persisted.
 */
export type NativeAndroidDeviceProfile = {
	profileId: string
	quality?: NativeAndroidHardwareProfile['quality']
	commercialName?: string
	fallback?: boolean
	manufacturer: string
	device: string
	osVersion: string
	osBuildNumber: string
	phoneId: string
	deviceExpId: string
	phoneIdTimestamp?: number
	perfDeviceId?: string
	mcc: string
	mnc: string
	localeLanguageIso6391: string
	localeCountryIso31661Alpha2: string
	deviceBoard?: string
	deviceModelType?: string
	yearClass?: number
	memClass?: number
	oc?: boolean
}

export type NativeAndroidPairingAttestation = {
	keyAttestation: Uint8Array
	gpia: Uint8Array | string
	/**
	 * The official WABA 2.26.27.83 fresh-QR flow emits this as the fourth
	 * pair-device-sign child, after key_attestation and an empty gpia node.
	 */
	clientAppId: Uint8Array | string
}

/** Dynamic values read by the official app from its remote configuration. */
export type NativeAndroidHistorySyncProfile = {
	fullSyncDaysLimit: number
	fullSyncSizeMbLimit: number
	thumbnailSyncDaysLimit: number
	supportGroupHistory: boolean
	onDemandReady: boolean
	supportHatchHistory: boolean
	supportedBotChannelFbids: string[]
}

export type NativeAndroidAttestationProvider = (context: {
	stanza: BinaryNode
	profileId: string
}) => Promise<NativeAndroidPairingAttestation>

export type NativeAndroidTransportConfig = {
	/** A second explicit gate in addition to transportProfile. */
	enabled: true
	host?: string
	port?: number
	/**
	 * Optional genuine ED routing bytes obtained from the official routing
	 * lifecycle. Existing persisted creds.routingInfo takes precedence.
	 */
	initialRoutingInfo?: Uint8Array
	appVersion: NativeAndroidAppVersion
	device: NativeAndroidDeviceProfile
	historySync: NativeAndroidHistorySyncProfile
	/**
	 * Returns genuine artifacts for the active device/challenge. No synthetic
	 * or attestation-free fallback is generated by the library.
	 */
	attestationProvider?: NativeAndroidAttestationProvider
}

export type PersistedNativeAndroidIdentity = {
	schemaVersion: 1
	profile: 'native_android'
	device: NativeAndroidDeviceProfile
	/**
	 * Successful-login counter sent as ClientPayload.lc. The official client
	 * reads the current value for the handshake and increments it only after
	 * the server's login-success node.
	 */
	connectionLc?: number
	/**
	 * Certified Noise responder static public key learned from a successful XX
	 * handshake. It is persisted for native Android IK reconnects and is never
	 * logged.
	 */
	serverStaticPublicKey?: Uint8Array
}
