import { Boom } from '@hapi/boom'
import { randomBytes, randomUUID } from 'crypto'
import { proto } from '../../WAProto/index.js'
import type { MetaAiPromptRequest } from '../Types/Message.js'
import { isJidBot, isJidGroup, isJidMetaAI, jidDecode, jidNormalizedUser } from '../WABinary/jid-utils'
import { hkdf } from './crypto'

/**
 * Prompt interaction observed in Android 2.26.37.6
 * (`BotMessageSendStanzaContributor`, jadx class `DHP`).
 */
export type MetaAiPromptType =
	| 'request_welcome'
	| 'prompt'
	| 'command'
	| 'search'
	| 'memu_onboarding'
	| 'memu_invoke'
	| 'voice'
	| 'voice_background'
	| 'text_input'
	| 'live_ai'
	| 'feedback'

export type MetaAiThreadType = 'default' | 'incognito' | 'side_chat'

export type MetaAiPersonaType = '1p' | 'ugc' | '3p'

export type MetaAiEntryPoint =
	| 'chat_shortcut'
	| 'context_menu'
	| 'invoke_1on1'
	| 'invoke_group'
	| 'forward'
	| 'ai_tab'
	| 'ai_home'
	| 'deeplink'

export type MetaAiThreadEntryPoint =
	| 'ai_tab_thread'
	| 'ai_home_thread'
	| 'ai_deeplink_immersive_thread'
	| 'ai_deeplink_thread'
	| 'ask_meta_ai_context_menu_thread'

export interface MetaAiThreadOptions {
	/** Stable UUID generated by the first prompt. Reuse it to continue a thread. */
	id?: string
	type?: MetaAiThreadType
	/** Required for side-chat threads started from another conversation. */
	sourceChatJid?: string
	title?: string
}

export interface MetaAiPromptOptions {
	/**
	 * Authoritative bot author JID. Direct prompts can omit it when `to` is
	 * already an FBID `@bot` JID. Group prompts must provide it.
	 */
	botJid?: string
	type?: MetaAiPromptType
	/** APK maps 1p/ugc/3p to `<bot persona_type="...">`. */
	personaType?: MetaAiPersonaType
	/** APK adds this only when the selected mode is available. */
	modeSelected?: string | number
	thread?: MetaAiThreadOptions
	personaId?: string
	invokerJid?: string
	entryPoint?: MetaAiEntryPoint
	threadEntryPoint?: MetaAiThreadEntryPoint
}

export interface MetaAiPromptMetadata {
	botJid: string
	clientThreadId: string
	type: MetaAiPromptType
	threadType: MetaAiThreadType
	sourceChatJid?: string
	title?: string
	createdNewThread: boolean
}

/**
 * Stable, motor-level Meta AI contract for HTTP gateways and SDKs. The
 * `MetaAiPromptRequest` fields remain available for advanced protocol needs,
 * while `threadId` gives consumers a simple way to continue a conversation.
 */
export interface MetaAiSendRequest extends MetaAiPromptRequest {
	/** Destination chat. A direct FBID `@bot` JID is the normal case. */
	to: string
	/** Plain text shown in the generated WhatsApp conversation message. */
	text: string
	/** Shortcut for `thread.id`; cannot be combined with `thread.id`. */
	threadId?: string
}

export interface NormalizedMetaAiSendRequest {
	to: string
	text: string
	options: MetaAiPromptOptions
}

export interface MetaAiSendResult {
	messageId: string | null
	chatJid: string | null
	botJid: string
	type: MetaAiPromptType
	threadId: string
	threadType: MetaAiThreadType
	createdNewThread: boolean
}

const ENTRY_POINTS = {
	chat_shortcut: proto.BotMetricsEntryPoint.META_AI_CHAT_SHORTCUT_AI_STUDIO,
	context_menu: proto.BotMetricsEntryPoint.ASK_META_AI_CONTEXT_MENU,
	invoke_1on1: proto.BotMetricsEntryPoint.INVOKE_META_AI_1ON1,
	invoke_group: proto.BotMetricsEntryPoint.INVOKE_META_AI_GROUP,
	forward: proto.BotMetricsEntryPoint.META_AI_FORWARD,
	ai_tab: proto.BotMetricsEntryPoint.AI_TAB,
	ai_home: proto.BotMetricsEntryPoint.AI_HOME,
	deeplink: proto.BotMetricsEntryPoint.AI_DEEPLINK
} as const

const THREAD_ENTRY_POINTS = {
	ai_tab_thread: proto.BotMetricsThreadEntryPoint.AI_TAB_THREAD,
	ai_home_thread: proto.BotMetricsThreadEntryPoint.AI_HOME_THREAD,
	ai_deeplink_immersive_thread: proto.BotMetricsThreadEntryPoint.AI_DEEPLINK_IMMERSIVE_THREAD,
	ai_deeplink_thread: proto.BotMetricsThreadEntryPoint.AI_DEEPLINK_THREAD,
	ask_meta_ai_context_menu_thread: proto.BotMetricsThreadEntryPoint.ASK_META_AI_CONTEXT_MENU_THREAD
} as const

const THREAD_TYPES = {
	default: proto.AIThreadInfo.AIThreadClientInfo.AIThreadType.DEFAULT,
	incognito: proto.AIThreadInfo.AIThreadClientInfo.AIThreadType.INCOGNITO,
	side_chat: proto.AIThreadInfo.AIThreadClientInfo.AIThreadType.SIDE_CHAT
} as const

const BOT_INFO = 'Bot Message'

/**
 * Stable public destination. The concrete FBID is transport data owned by the
 * motor and must not become part of the product API contract.
 */
export const META_AI_PUBLIC_ALIAS = '@bot_meta_ai'
export const META_AI_INTERNAL_BOT_JID = '718584497008509@bot'
const META_AI_INTERNAL_BOT_USER = META_AI_INTERNAL_BOT_JID.split('@')[0]

const normalizeDestination = (value: string) => value.trim().toLowerCase()

export const isPublicMetaAiDestination = (value: string | undefined): boolean =>
	normalizeDestination(value || '') === META_AI_PUBLIC_ALIAS

export const resolveMetaAiTransportDestination = (value: string): string =>
	isPublicMetaAiDestination(value) ? META_AI_INTERNAL_BOT_JID : value.trim()

export const toPublicMetaAiDestination = (value: string | undefined): string | undefined => {
	const decoded = jidDecode(value || '')
	return decoded?.server === 'bot' && decoded.user === META_AI_INTERNAL_BOT_USER ? META_AI_PUBLIC_ALIAS : value
}

export const resolveMetaAiPrompt = (
	to: string,
	options: MetaAiPromptOptions | undefined
): (MetaAiPromptOptions & { resolvedBotJid: string }) | undefined => {
	const directBot = isPublicMetaAiDestination(to) || isJidMetaAI(to)
	const legacyBot = isJidBot(to) || isJidBot(jidNormalizedUser(to))

	if (directBot) {
		return {
			...(options || {}),
			resolvedBotJid: isPublicMetaAiDestination(to) ? META_AI_INTERNAL_BOT_JID : to
		}
	}

	if (legacyBot) {
		const requestedBot = options?.botJid
		if (requestedBot && !isJidMetaAI(requestedBot) && jidNormalizedUser(requestedBot) !== jidNormalizedUser(to)) {
			throw new Error('Meta AI botJid must be an @bot JID or match the legacy bot destination')
		}

		return { ...(options || {}), resolvedBotJid: requestedBot || to }
	}

	const requestedBot = options?.botJid
	if (isJidGroup(to) && requestedBot && isJidMetaAI(requestedBot)) {
		return { ...options, resolvedBotJid: requestedBot }
	}

	return undefined
}

export const buildMetaAiPromptContext = (
	to: string,
	options: MetaAiPromptOptions | undefined,
	meId: string,
	rootMessageSecret?: Uint8Array
): {
	botNode: { attrs: Record<string, string> }
	botMetadata: proto.IBotMetadata
	metadata: MetaAiPromptMetadata
	messageSecret: Buffer
	botMessageSecret: Buffer
} => {
	const resolved = resolveMetaAiPrompt(to, options)
	if (!resolved) throw new Error('Meta AI prompt requires an @bot JID or an explicit group botJid')

	const clientThreadId = resolved.thread?.id || randomUUID()
	const threadType = resolved.thread?.type || 'default'
	if (threadType === 'side_chat' && !resolved.thread?.sourceChatJid) {
		throw new Error('Meta AI side_chat thread requires metaAi.thread.sourceChatJid')
	}

	const botMetadata: proto.IBotMetadata = {
		personaId: resolved.personaId,
		invokerJid: resolved.invokerJid || meId,
		botMetricsMetadata: {
			destinationId: resolved.resolvedBotJid,
			destinationEntryPoint: resolved.entryPoint
				? ENTRY_POINTS[resolved.entryPoint]
				: isJidGroup(to)
					? ENTRY_POINTS.invoke_group
					: ENTRY_POINTS.invoke_1on1,
			threadOrigin: resolved.threadEntryPoint ? THREAD_ENTRY_POINTS[resolved.threadEntryPoint] : undefined
		},
		botThreadInfo: {
			serverInfo: resolved.thread?.title ? { title: resolved.thread.title } : undefined,
			clientInfo: {
				type: THREAD_TYPES[threadType],
				sourceChatJid: resolved.thread?.sourceChatJid
			}
		}
	}

	const attrs: Record<string, string> = {
		type: resolved.type || 'prompt',
		client_thread_id: clientThreadId
	}
	if (resolved.personaType) attrs.persona_type = resolved.personaType
	if (resolved.modeSelected !== undefined) attrs.mode_selected = String(resolved.modeSelected)

	// Android creates the ordinary message secret, derives
	// botMessageSecret = HKDF(messageSecret, info="Bot Message"), sends only the
	// derived value in MessageContextInfo, and removes the original (jadx
	// `C29311Cqv`). We retain the original only in the per-socket msmsg cache.
	const messageSecret = rootMessageSecret?.byteLength === 32 ? Buffer.from(rootMessageSecret) : randomBytes(32)
	const botMessageSecret = Buffer.from(hkdf(messageSecret, 32, { info: BOT_INFO }))

	return {
		botNode: { attrs },
		botMetadata,
		metadata: {
			botJid: resolved.resolvedBotJid,
			clientThreadId,
			type: resolved.type || 'prompt',
			threadType,
			sourceChatJid: resolved.thread?.sourceChatJid,
			title: resolved.thread?.title,
			createdNewThread: !resolved.thread?.id
		},
		messageSecret,
		botMessageSecret
	}
}

export const normalizeMetaAiSendRequest = (request: MetaAiSendRequest): NormalizedMetaAiSendRequest => {
	const requestedTo = typeof request.to === 'string' ? request.to.trim() : ''
	const text = typeof request.text === 'string' ? request.text : ''
	if (!requestedTo || !text.trim()) throw new Error('Meta AI send requires to and text')

	const threadId = typeof request.threadId === 'string' ? request.threadId.trim() : ''
	const nestedThreadId = typeof request.thread?.id === 'string' ? request.thread.id.trim() : ''
	const resolvedThreadId = threadId || nestedThreadId
	if (threadId && nestedThreadId && threadId !== nestedThreadId) {
		throw new Error('Use either threadId or thread.id, not different values')
	}

	const source = { ...request } as Partial<MetaAiSendRequest> & MetaAiPromptOptions
	delete source.to
	delete source.text
	delete source.threadId
	delete source.thread
	// The thread object is always rebuilt below from `resolvedThreadId`,
	// never copied raw from the request. A `thread.id` that trims to empty
	// must produce the same result as a `threadId` that trims to empty.
	const normalizedThread = resolvedThreadId
		? { ...(request.thread || {}), id: resolvedThreadId }
		: request.thread && Object.keys(request.thread).some(k => k !== 'id')
			? // Preserve legitimate fields (type, sourceChatJid) when only the id is blank.
				{ ...request.thread, id: undefined }
			: undefined
	const normalizedOptions: MetaAiPromptOptions = {
		...source,
		...(normalizedThread ? { thread: normalizedThread } : {})
	}
	if (resolvedThreadId && !normalizedOptions.type) normalizedOptions.type = 'text_input'

	// Resolve here so a public client gets a deterministic validation error
	// instead of accidentally sending an ordinary conversation message.
	if (!resolveMetaAiPrompt(requestedTo, normalizedOptions)) {
		throw new Error('Meta AI send requires a direct @bot destination or a group with metaAi.botJid')
	}

	return { to: resolveMetaAiTransportDestination(requestedTo), text, options: normalizedOptions }
}

export const assertMetaAiPromptMetadata = (metadata: MetaAiPromptMetadata): void => {
	if (
		!metadata.botJid ||
		!metadata.clientThreadId ||
		!metadata.type ||
		!metadata.threadType ||
		typeof metadata.createdNewThread !== 'boolean'
	) {
		throw new Boom('Meta AI prompt metadata is incomplete', { statusCode: 500 })
	}
}

export const buildMetaAiSendResult = (
	message: { key?: { id?: string | null; remoteJid?: string | null } },
	metadata: MetaAiPromptMetadata
): MetaAiSendResult => {
	assertMetaAiPromptMetadata(metadata)

	return {
		messageId: message.key?.id || null,
		chatJid: toPublicMetaAiDestination(message.key?.remoteJid || undefined) || null,
		botJid: toPublicMetaAiDestination(metadata.botJid) || '',
		type: metadata.type,
		threadId: metadata.clientThreadId,
		threadType: metadata.threadType,
		createdNewThread: metadata.createdNewThread
	}
}
